# Site settings
author: David J Forer
title: Web Development Overload
header-img: img/home-bg.png
email: david.j.forer@gmail.com
copyright_name: David J Forer
description: > # this means to ignore newlines until "baseurl:"
  The Opportunity Within to Overcome and Achieve with Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  david-forer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
